### ISSUE TITLE
Timeout in RubyMine's Evaluate Expression window when running selenium-webdriver commands (Ruby 2.3.x) 

### ISSUE THREAD

**Issue by stevegibson** [ruby-debug/ruby-debug-ide#80] opened 2016-07-14 20:01 UTC
In Ruby 2.3.0 (and beyond), when running selenium commands (selenium-webdriver gem, v. 2.53.4) in the Evaluate Expression (i.e. @browser.get('http://www.google.com')) of RubyMine, the command eventually times out with the attached stack trace. Please note that stepping over selenium commands in the debugger (not in the Evaluate Expression window), after setting a breakpoint, works fine. It's just when I'm executing them inside the Evaluate Expression window of RubyMine that I'm seeing the problem.

This was working in Ruby 2.1.6.

Relevant environment information:
OS: OSX 10.11.5
Browser: FF v. 45.0.1 and Chrome (latest)
IDE: RubyMine: 2016.1 (and also 2016.2 EAP)
Ruby: 2.3.0 and 2.3.1
Selenium-webdriver: 2.53.4

![image](https://cloud.githubusercontent.com/assets/1478920/16853460/6b850f1c-49da-11e6-9ec0-845eaac2b34b.png)

**Comment by stevegibson** [comment] 2016-07-18 12:24
Per [this stackoverflow question](http://stackoverflow.com/questions/38258731/cannot-evaluate-html-elements-in-rubymine-using-ruby-2-3-0), this is also happening with Watir-webdriver.

**Comment by denofevil** [comment] 2016-07-22 14:15
This seems to be caused by introduction of 60s ``@open_timeout`` in http.rb. It used to be nil, so no additional threads were spawned. Now, with 60s it spawns a new thread, which cannot run as the process is stopped on the breakpoint, so it timeouts there.

Minimal case would look like this:
```ruby
require 'timeout'

def compute_with_timeout
  Timeout.timeout(10) { Thread.list }
end
with = compute_with_timeout #breakpoint here
puts with
```

**Comment by luke-hill** [comment] 2017-05-04 12:08
Sorry to bump a really old thread. Did this get anywhere?

**Comment by xenjke** [comment] 2017-05-04 12:13
```ruby
class OverrideDriver < Selenium::WebDriver::Remote::Http::Default
  def http
    client = super
    client.open_timeout = 0
    client
  end
end

# when creating driver instance
Watir.new(:chrome, http_client: OverrideDriver.new)
```
that solves the issue for me

**Comment by luke-hill** [comment] 2017-05-04 12:20
@xenjke Are you using Se3+?

**Comment by xenjke** [comment] 2017-05-04 12:26
@luke-hill 3.4.0 it is

**Comment by xenjke** [comment] 2017-05-04 12:37
@luke-hill another workaround mentioned in https://youtrack.jetbrains.com/issue/RUBY-17930#comment=27-1794364 is to monkeypatch the Timeout module for debugging purposes only.

Do not use that on production.

```
module Timeout
  def timeout(sec, klass=nil)
    yield(sec)
  end
  module_function :timeout
end
```

**Comment by xenjke** [comment] 2017-05-04 12:56
came up with

```
if $LOADED_FEATURES.any? { |f| f.include? 'debase' }
  module Timeout
    def timeout(sec, klass=nil)
      yield(sec)
    end

    module_function :timeout
  end
end
```

**Comment by luke-hill** [comment] 2017-05-04 13:06
@xenjke The original one works when I implement it as written (I tried a slightly shorter version).

I'd rather know why this has happened. I had a look at the docs and I have traced the file in RubyMine, but as I'm using Se2.53 I'm not sure why this is happening.

Either way your fix works, I just hope RubyMine fix it up their end if possible

**Comment by luke-hill** [comment] 2017-12-22 10:41
This issue can be closed as fixed.

For readers: Use at least RubyMine 2017.2.x and either
Ruby `2.2`
or
Ruby `2.3`+ and Selenium `3.0.7`+

**Comment by valich** [comment] 2017-12-22 13:55
@luke-hill There is still an issue with incorrect thread usage for timeout, #128 should make ruby use another thread for evaluation. It's targeted to 2018.1

**Closed** 2018-03-13 14:24 UTC
